//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Item
    {
        public int ItemID { get; set; }
        [DisplayName("Item Name")]
        public string ItemName { get; set; }
        [ForeignKey("Tops")]
        public int TopID { get; set; }
        [ForeignKey("Bottoms")]
        public int BottomID { get; set; }
        [ForeignKey("Shoes")]
        public int ShoeID { get; set; }
        [ForeignKey("Accesories")]
        public int AccessoryID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Shoe Shoe { get; set; }
        public virtual Top Top { get; set; }
    }
}
